# Generated by Django 3.1.7 on 2021-04-12 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='checkout_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
