# Generated by Django 3.1.7 on 2021-04-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_requests', '0002_bookrequest_checkout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='checkout_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
