# Generated by Django 3.1.7 on 2021-04-03 18:03

import accounts.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone_confirmation_number',
            field=models.CharField(default=accounts.helpers.generate_confirmation_number, max_length=32),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
