# Generated by Django 3.1.7 on 2021-04-03 20:23

import accounts.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210403_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='invite_number',
            field=models.CharField(default=accounts.helpers.generate_confirmation_number, max_length=32),
        ),
    ]
